# **`Pandas Practice`**

In [2]:
import pandas as pd

In [3]:
Data = pd.read_csv("Titanic-Dataset.csv")

In [4]:
Data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
Data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [6]:
Data.shape

(891, 12)

In [7]:
Data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
Data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [11]:
Data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [16]:
print("\n Selecting Rows by Index ")
print(Data.iloc[0:3])
print(Data.loc[0:4])  


 Selecting Rows by Index 
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0            

In [18]:
print("\n Filter: Age > 35")
print(Data[Data["Age"] > 35])



 Filter: Age > 35
     PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                

# **`NumPy Practice`**

In [20]:
import numpy as np

In [21]:
names = np.array(["Amit", "Riya", "John", "Sara", "Dev"])
ages = np.array([22, 25, 24, 23, 26])
scores = np.array([88, 92, 79, 95, 85])
cities = np.array(["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"])

print("\n=== Original NumPy Dataset ===")
print("Names :", names)
print("Ages  :", ages)
print("Scores:", scores)
print("Cities:", cities)


=== Original NumPy Dataset ===
Names : ['Amit' 'Riya' 'John' 'Sara' 'Dev']
Ages  : [22 25 24 23 26]
Scores: [88 92 79 95 85]
Cities: ['Delhi' 'Mumbai' 'Delhi' 'Bangalore' 'Mumbai']


In [22]:
print("\n=== Basic Operations ===")
print("Ages + 2:", ages + 2)
print("Scores * 2:", scores * 2)
print("Scores / 10:", scores / 10)

# Slicing
print("\nAges first 3:", ages[:3])
print("Scores last 2:", scores[-2:])


=== Basic Operations ===
Ages + 2: [24 27 26 25 28]
Scores * 2: [176 184 158 190 170]
Scores / 10: [8.8 9.2 7.9 9.5 8.5]

Ages first 3: [22 25 24]
Scores last 2: [95 85]


In [23]:
print("\n=== NumPy Statistics ===")
print("Average Age:", np.mean(ages))
print("Max Score:", np.max(scores))
print("Min Score:", np.min(scores))
print("Std Deviation of Score:", np.std(scores))
print("Median Score:", np.median(scores))


=== NumPy Statistics ===
Average Age: 24.0
Max Score: 95
Min Score: 79
Std Deviation of Score: 5.564171097297422
Median Score: 88.0


In [27]:
print("\n=== Filtering ===")

# Score > 85
high_scores = scores > 85
print("Scores > 85:", scores[high_scores])
print("Names with Score > 85:", names[high_scores])

# City = Delhi
delhi_students = cities == "Delhi"
print("\nDelhi Students:", names[delhi_students])

# Combined Condition: Age > 23 AND Score > 85
cond = (ages > 23) & (scores > 85)
print("\nAge > 23 & Score > 85:", names[cond])


=== Filtering ===
Scores > 85: [88 92 95]
Names with Score > 85: ['Amit' 'Riya' 'Sara']

Delhi Students: ['Amit' 'John']

Age > 23 & Score > 85: ['Riya']


In [31]:
# Create matrix of Age & Score
matrix = np.vstack((ages, scores))
print("\n=== Matrix ===")
print(matrix)

print("\nTranspose:")
print(matrix.T)

print("\nDot Product of Age row and Score row:")
print(np.dot(ages, scores))


=== Matrix ===
[[22 25 24 23 26]
 [88 92 79 95 85]]

Transpose:
[[22 88]
 [25 92]
 [24 79]
 [23 95]
 [26 85]]

Dot Product of Age row and Score row:
10527


In [33]:
scores_with_nan = scores.astype(float)
scores_with_nan[2] = np.nan  # inserting missing value

print("\n=== Scores with NaN ===")
print(scores_with_nan)

# Replace NaN with mean
mean_val = np.nanmean(scores_with_nan)
filled_scores = np.nan_to_num(scores_with_nan, nan=mean_val)

print("NaN Replaced with Mean:", filled_scores)


=== Scores with NaN ===
[88. 92. nan 95. 85.]
NaN Replaced with Mean: [88. 92. 90. 95. 85.]
